### ISSUE TITLE
Unable to run tuning script

### ISSUE THREAD

**Issue by jamesdbaker** [ivan-zapreev/Basic-Translation-Infrastructure#10]
When running the tuning script, I get some errors in the logs and the tuning script appears to fail.

The commands I'm running (with seemingly unnecessary bits truncated) is:
```
$ cd tuning
$ ls
forums.en.1  forums.fr  server.cfg

$ ~/Distributed-Translation-Infrastructure/script/tuning/run_tuning.pl  --conf=server.cfg --src-language=French --src=/home/bakerj/tuning/forums.fr --ref=/home/bakerj/tuning/forums.en --trg-language=English --trace=3
...

$ ~/Distributed-Translation-Infrastructure/script/tuning/tuning_progress.pl  --conf=server.cfg --err=tuning.log
Smartmatch is experimental at /home/bakerj/Distributed-Translation-Infrastructure/script/tuning/tuning_progress.pl line 124.
ERROR: Can't open file .server.cfg.work.feature_id2name: No such file or directory

$ cat tuning.log
tuner.pl pid=67560
readline() on closed filehandle FEATURES_MAPPING_FILE at /home/bakerj/Distributed-Translation-Infrastructure/script/tuning/scripts/load_config_file.pl line 172.
/home/bakerj/Distributed-Translation-Infrastructure/script/tuning/scripts/../PRO/PRO-optimization-procedure.pl ... --lambda-string='' ...
Option lambda-string requires an argument
...
```

**Comment by jamesdbaker** [comment]
I think I may have resolved this, I ran again using a version where bpbd-server had been compiled with `IS_SERVER_TUNING_MODE` enabled and it now seems to be working.

This wasn't clear in the documentation as a requirement, so I will submit an update to the documentation.

**Comment by ivan-zapreev** [comment]
Dear James,

Sorry I did not spot the issue right away. It seems that the e-mail notifications digest I get is not that regular. If something, in addition to submitting an issue, please feel free to also contact me directly via my private e-mail.

Kind regards,

Ivan

**Comment by ivan-zapreev** [comment]
Re-opening the issue as an error shall be issued in case of a configuration/compilation parameters mismatch!

**Comment by ivan-zapreev** [comment]
Fixed in https://github.com/ivan-zapreev/Distributed-Translation-Infrastructure/commit/4d76a8d4299bb2bae044a63ed4ccc95de947c074
