### ISSUE TITLE
setting log level 

### ISSUE THREAD

**Issue by hamidreza-ghader** [ivan-zapreev/Basic-Translation-Infrastructure#2]
In the documentation it has been mentioned that one has to set LOGER_M_GRAM_LEVEL_MAX constant value in the ./inc/common/utils/logging/logger.hpp header file to change the log level, while the mentioned constant does not exist in the hpp file and the constant name seems to be MAXIMUM_LOGGING_LEVEL.

**Comment by ivan-zapreev** [comment]
Fixed :+1:
