### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by hamidreza-ghader** [ivan-zapreev/Basic-Translation-Infrastructure#3]
CMakeFiles/bpbd-processor.dir/src/processor/bpbd_processor.cpp.o: In function `uva::smt::bpbd::processor::processor_manager::notify_job_done(uva::smt::bpbd::processor::processor_job*)':
bpbd_processor.cpp:(.text._ZN3uva3smt4bpbd9processor17processor_manager15notify_job_doneEPNS2_13processor_jobE[_ZN3uva3smt4bpbd9processor17processor_manager15notify_job_doneEPNS2_13processor_jobE]+0x5f): undefined reference to`uva::smt::bpbd::processor::operator<<(std::ostream&, uva::smt::bpbd::processor::processor_job const&)'
CMakeFiles/bpbd-processor.dir/src/processor/bpbd_processor.cpp.o: In function `uva::smt::bpbd::processor::processor_manager::schedule_new_job(uva::smt::bpbd::processor::processor_job*)':
bpbd_processor.cpp:(.text._ZN3uva3smt4bpbd9processor17processor_manager16schedule_new_jobEPNS2_13processor_jobE[_ZN3uva3smt4bpbd9processor17processor_manager16schedule_new_jobEPNS2_13processor_jobE]+0x4f): undefined reference to`uva::smt::bpbd::processor::operator<<(std::ostream&, uva::smt::bpbd::processor::processor_job const&)'
bpbd_processor.cpp:(.text._ZN3uva3smt4bpbd9processor17processor_manager16schedule_new_jobEPNS2_13processor_jobE[_ZN3uva3smt4bpbd9processor17processor_manager16schedule_new_jobEPNS2_13processor_jobE]+0x123): undefined reference to `uva::smt::bpbd::processor::operator<<(std::ostream&, uva::smt::bpbd::processor::processor_job const&)'

**Comment by ivan-zapreev** [comment]
Added the stream output operator.
