### ISSUE TITLE
Problem loading config file

### ISSUE THREAD

**Issue by hamidreza-ghader** [ivan-zapreev/Basic-Translation-Infrastructure#4]
The server cannot parse the config file properly when lambda values are in high precision. Here I have provided some lambda values to be used in a config file. The order of the lambda values is the same order as in server.cfg.feature_id2name file.

-0.000162457848383319 0.247927209374343 0.0355422983635898 0.0148346801128702 0.00169563839872649 -0.00867862339385234 0.015074386107116 0.0133560971821781 0.0189869657925356 0.0329663066094344 0.01456172599588 0.00776403068125194 0.037211847543291 0.0571065223939
879 0.0506461063759449 0.0024456905316676

**Comment by ivan-zapreev** [comment]
The INI library had a limited size buffer of 128 bytes to read config file lines, this buffer is now increased to 1024 characters, which should be enough.
